# Generated by Django 4.2.13 on 2024-06-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='visaCategory',
            field=models.CharField(default='Bachelor students holding an unconditional direct admission letter from a German university valid for winter semester 2024-2025 / Bachelorstudenten mit direkter Zulassung ohne Bedingungen für das Wintersemester 2024-2025', max_length=100),
            preserve_default=False,
        ),
    ]
