# Generated by Django 4.2.13 on 2024-06-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userdata_visacategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='formEmail',
            field=models.CharField(default='bsai23031@itu.edu.pk', max_length=100),
            preserve_default=False,
        ),
    ]
