# Generated by Django 4.2.13 on 2024-06-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userdata_formemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='citizenship',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='visaCategory',
            field=models.IntegerField(),
        ),
    ]
