# Generated by Django 4.2.13 on 2024-06-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_userdata_citizenship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='citizenship',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='visaCategory',
            field=models.CharField(max_length=100),
        ),
    ]
